#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Daalvand\Safar724AutoTrack\Console\Commands\TicketTrackerCommand;
use Dotenv\Dotenv;
use Symfony\Component\Console\Application;

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();

$app = new Application();
$app->add(new TicketTrackerCommand());
$app->run();