#!/usr/bin/env php
<?php

date_default_timezone_set('Asia/Tehran');

require_once __DIR__ . '/vendor/autoload.php';

use Daalvand\Safar724AutoTrack\Console\Commands\ReserveTicketCommand;
use Daalvand\Safar724AutoTrack\Console\Commands\TicketTrackerCommand;
use Dotenv\Dotenv;
use Symfony\Component\Console\Application;

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();

$app = new Application();
$app->add(new TicketTrackerCommand());
$app->add(new ReserveTicketCommand());

$app->run();